# Generated by Django 5.1.7 on 2025-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('temps_preparation', models.IntegerField()),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
