# Generated by Django 5.1.7 on 2025-05-10 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('legumes', 'Légumes'), ('viandes', 'Viandes et Volailles'), ('produits_laitiers', 'Produits Laitiers et Œufs'), ('epicerie', 'Épicerie'), ('fruits', 'Fruits'), ('herbes', 'Herbes et Épices')], max_length=50)),
            ],
            options={
                'verbose_name': 'Ingrédient',
                'verbose_name_plural': 'Ingrédients',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='recette',
            options={'ordering': ['nom'], 'verbose_name': 'Recette', 'verbose_name_plural': 'Recettes'},
        ),
        migrations.AddField(
            model_name='recette',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recette',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.RemoveField(
            model_name='recette',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la recette'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_preparation',
            field=models.IntegerField(verbose_name='Temps de préparation (minutes)'),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.ManyToManyField(to='base.ingredient', verbose_name='Ingrédients'),
        ),
    ]
