# Generated by Django 5.1.7 on 2025-05-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ingredient_alter_recette_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recettes/', verbose_name='Image de la recette'),
        ),
    ]
