# Generated by Django 5.1.7 on 2025-05-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_recette_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favori'),
        ),
        migrations.AddField(
            model_name='recette',
            name='portions',
            field=models.IntegerField(default=4, verbose_name='Nombre de portions'),
        ),
    ]
